// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    App: typeof import('./src/app.vue')['default']
    AppHeader: typeof import('./src/common/app-header.vue')['default']
    AppLoadingBar: typeof import('./src/common/app-loading-bar.vue')['default']
    AppThemeButton: typeof import('./src/common/app-theme-button.vue')['default']
    AppUserButton: typeof import('./src/common/app-user-button.vue')['default']
    AppUserPopover: typeof import('./src/common/app-user-popover.vue')['default']
    FaAnkh: typeof import('@vicons/fa')['Ankh']
    FaMoon: typeof import('@vicons/fa')['Moon']
    FaSun: typeof import('@vicons/fa')['Sun']
    FaUser: typeof import('@vicons/fa')['User']
    HomeView: typeof import('./src/views/home-view.vue')['default']
    NAvatar: typeof import('naive-ui')['NAvatar']
    NButton: typeof import('naive-ui')['NButton']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NGlobalStyle: typeof import('naive-ui')['NGlobalStyle']
    NH1: typeof import('naive-ui')['NH1']
    NIcon: typeof import('naive-ui')['NIcon']
    NImage: typeof import('naive-ui')['NImage']
    NImg: typeof import('naive-ui')['NImg']
    NLayoutHeader: typeof import('naive-ui')['NLayoutHeader']
    NLoadingBarProvider: typeof import('naive-ui')['NLoadingBarProvider']
    NPageHeader: typeof import('naive-ui')['NPageHeader']
    NPopover: typeof import('naive-ui')['NPopover']
    NSpace: typeof import('naive-ui')['NSpace']
    NText: typeof import('naive-ui')['NText']
    PostView: typeof import('./src/views/post-view.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    XAnkh: typeof import('@vicons/fa')['Ankh']
  }
}
