// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    App: typeof import('./src/app.vue')['default']
    AppHeader: typeof import('./src/common/app-header.vue')['default']
    FaAnkh: typeof import('@vicons/fa')['Ankh']
    FaSun: typeof import('@vicons/fa')['Sun']
    HomeView: typeof import('./src/views/home-view.vue')['default']
    NAvatar: typeof import('naive-ui')['NAvatar']
    NButton: typeof import('naive-ui')['NButton']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NGlobalStyle: typeof import('naive-ui')['NGlobalStyle']
    NH1: typeof import('naive-ui')['NH1']
    NIcon: typeof import('naive-ui')['NIcon']
    NLayoutHeader: typeof import('naive-ui')['NLayoutHeader']
    NPageHeader: typeof import('naive-ui')['NPageHeader']
    NSpace: typeof import('naive-ui')['NSpace']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    XAnkh: typeof import('@vicons/fa')['Ankh']
  }
}
