import type { LanguageSupportMode } from "./language-support";

const names: Record<LanguageSupportMode, string> = {
  apl: "A Programming Language (APL)",
  asciiArmor: "ASCII Armor (PGP)",
  asn1: "Abstract Syntax Notation One (ASN.1)",
  asterisk: "Asterisk",
  brainfuck: "Brainfuck",
  c: "C",
  cassandra: "Cassandra Query Language (CQL)",
  ceylon: "Ceylon",
  clojure: "Clojure",
  cmake: "CMake",
  cobol: "Cobol",
  coffeeScript: "CoffeeScript",
  commonLisp: "Common Lisp",
  commonmark: "Markdown",
  cpp: "C++",
  crystal: "Crystal",
  csharp: "C#",
  css: "CSS",
  cypher: "Cypher",
  cython: "Cython",
  d: "D",
  dart: "Dart",
  diff: "diff",
  dockerFile: "Dockerfile",
  dtd: "Document Type Definition (DTD)",
  dylan: "Dylan",
  ebnf: "Extended Backus-Naur Form (EBNF)",
  ecl: "Enterprise Control Language (ECL)",
  eiffel: "Eiffel",
  elm: "Elm",
  erlang: "Erlang",
  esper: "Esper",
  ez80: "Assembler (eZ80)",
  factor: "Factor",
  fcl: "Fuzzy Control Language (FCL)",
  forth: "Forth",
  fortran: "Fortran",
  fSharp: "F#",
  gas: "Assembler (GNU)",
  gasArm: "Assembler (GNU, ARM)",
  gherkin: "Gherkin",
  go: "Go",
  gpSQL: "Greenplum SQL (GPSQL)",
  gql: "Google Query Language (GQL)",
  groovy: "Apache Groovy",
  gss: "Closure Stylesheets (GSS)",
  haskell: "Haskell",
  haxe: "Haxe",
  hive: "Hive",
  html: "HTML",
  http: "HTTP",
  hxml: "HXML",
  idl: "Interface Definition Language (IDL)",
  java: "Java",
  javascript: "JavaScript",
  jinja2: "Jinja2",
  json: "JSON",
  jsonld: "JSON-LD",
  jsx: "Javascript (JSX)",
  julia: "Julia",
  kotlin: "Kotlin",
  less: "LESS",
  liveScript: "LiveScript",
  lua: "Lua",
  mariaDB: "MariaDB SQL",
  markdown: "Markdown (GitHub Flavored)",
  mathematica: "Mathematica",
  mbox: "mbox",
  mirc: "mIRC",
  modelica: "Modelica",
  mscgen: "MSC Generator",
  msgenny: "MsGenny",
  msSQL: "Microsoft SQL Server",
  mumps: "MUMPS",
  mySQL: "MySQL",
  nesC: "Network Embedded Systems C (NesC)",
  nginx: "Nginx",
  nsis: "NSIS",
  ntriples: "NTriples",
  objectiveC: "Objective-C",
  objectiveCpp: "Objective-C++",
  oCaml: "OCaml",
  octave: "Octave",
  oz: "Oz",
  pascal: "Pascal",
  pegjs: "PEG.js",
  perl: "Perl",
  pgSQL: "PostgreSQL",
  php: "PHP",
  pig: "Apache Pig",
  plSQL: "PL/SQL",
  powerShell: "PowerShell",
  properties: "Properties",
  protobuf: "Protocol Buffers",
  puppet: "Puppet",
  python: "Python",
  q: "Q",
  r: "R",
  rpmChanges: "RPM Changes",
  rpmSpec: "RPM Spec",
  ruby: "Ruby",
  rust: "Rust",
  sas: "SAS",
  sass: "Sass",
  scala: "Scala",
  scheme: "Scheme",
  sCSS: "SCSS",
  shader: "Shader",
  shell: "Shell",
  sieve: "Sieve",
  smalltalk: "Smalltalk",
  sml: "Standard ML (SML)",
  solr: "Apache Solr",
  sparkSQL: "Spark SQL",
  sparql: "SPARQL",
  spreadsheet: "Spreadsheet",
  sqlite: "SQLite",
  squirrel: "Squirrel",
  standardSQL: "Standard SQL",
  stex: "LaTeX",
  stexMath: "sTeX",
  stylus: "Stylus",
  swift: "Swift",
  tcl: "Tcl",
  textile: "Textile",
  tiddlyWiki: "TiddlyWiki",
  tiki: "Tiki Wiki",
  tlv: "TL-Verilog",
  toml: "TOML",
  troff: "Troff",
  tsx: "TypeScript (JSX)",
  ttcn: "TTCN",
  ttcnCfg: "TTCN Configuration",
  turtle: "Turtle",
  typescript: "TypeScript",
  vb: "VB.NET",
  vbScript: "VBScript",
  vbScriptASP: "VBScript ASP",
  velocity: "Velocity",
  verilog: "Verilog",
  vhdl: "VHDL",
  wast: "WebAssembly",
  webIDL: "Web IDL",
  xml: "XML",
  xQuery: "XQuery",
  xu: "Xu",
  yacas: "Yacas",
  yaml: "YAML",
  z80: "Assembler (Z80)",
};

export default names;
